### ISSUE TITLE
Not functional in Private Mode

### ISSUE THREAD

**Issue by Athesis** [NatePri/Raccoony#11]
For some reasons the Addon dosn't work in Private Mode. I'm using Version 46.0.1 of Firefox on Windows 10.

**Comment by NatePri** [comment]
Hm, looks like I need to add something to the manifest to enable it to work in Private mode; shouldn't be too hard.

(also congrats on being the first besides me to log a bug n.n)

**Comment by Athesis** [comment]
Hehe, sure - I'll really like your plugin :+1:

**Comment by NatePri** [comment]
Thanks! n.n
Should be fixed in the 0.0.19 release I just pushed. Let me know if you still see problems after updating.
