### ISSUE TITLE
"Open all in tabs" in Private-Mode opens new Windows in Normal-Mode

### ISSUE THREAD

**Issue by Athesis** [NatePri/Raccoony#18]
Hi,

First; Thanks for adding Private-Mode possibillity :+1: !

But I found a new bug: If I klick on "Opeb all in tabs" at Furaffinity everything will open in a new, non-private Window.

**Comment by NatePri** [comment]
Oh wow, so it does. Lemme see if there's anything I can do about that.

On 5/30/2016 11:10 AM, Athesis wrote:
>
> Hi,
>
> First; Thanks for adding Private-Mode possibillity 👍 !
>
> But I found a new bug: If I klick on "Opeb all in tabs" at Furaffinity 
> everything will open in a new, non-private Window.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/NatePri/Raccoony/issues/18>, or mute the thread 
> <https://github.com/notifications/unsubscribe/ACHInueiA_IMqqiTbCfprgSNHVtR2Lj0ks5qGygygaJpZM4Ip9pU>.
>

-- 
-Simon

**Comment by NatePri** [comment]
Hmm... well, I can fix it to always open private windows, but it looks like it'll intermittently decide that it needs to open new windows rather than new tabs in the current window, and I'm not sure why. It looks like it only does it the first time you use the Open in Tabs feature from a private window for some reason.

**Comment by NatePri** [comment]
Okay, I've updated it with a fix; unfortunately, you may need to click "open all" twice the first time as I couldn't figure out a better way to take care of the weird new-window behavior.

**Comment by Athesis** [comment]
Works fine for me :)!

**Comment by NatePri** [comment]
Awesome. Thanks for the report!
