### ISSUE TITLE
Description and Tags download

### ISSUE THREAD

**Issue by Athesis** [NatePri/Raccoony#19]
Hi,

It would be great if it would be possible to also save the Description and Tags of the Image.

**Comment by NatePri** [comment]
Hmm... like save it in the EXIF data for the image, or as part of the filename? EXIF might be a bit tricky as I'm not sure if there's a JS library that can read/write that data, and I'm not sure that I'm up for writing my own.

I could also save it in a separate file next to the image, but that strikes me as a bit inconvenient.

**Comment by Athesis** [comment]
Textfile would be nice alredy - Exif has a limit at around 64000 Byte with any information. And then there are also gif, png, tif .... Yes, textfile is alright and well searchable by Windows and Linux - And for peoples who like to get more also convertable.

**Comment by NatePri** [comment]
Text file should be doable. I'll look into adding that in my next release.

**Comment by NatePri** [comment]
This is now available in the 0.0.21 release but is disabled by default. You can enable it via the add-on options page for Raccoony.

**Comment by Athesis** [comment]
Great, works super <3!
