### ISSUE TITLE
Furaffinity Text- and Tagsuppot

### ISSUE THREAD

**Issue by Athesis** [NatePri/Raccoony#22]
Hi,

The Support for downloading Text and Tags on Furaffinity dosn't work anymore :(

**Comment by NatePri** [comment]
Most likely happened after the most recent UI revision. Do you use the Beta UI? Or the Classic UI?

**Comment by Athesis** [comment]
Hi, 
I tryed both without any luck. There is just "Error downloading [object Object]"

Here is the HTML I got from FA (classic); http://pastebin.com/TgYhi6Ha

**Comment by NatePri** [comment]
Just pushed a fix, please update and let me know if you still see the issue.

**Comment by Athesis** [comment]
Works fine, Thanks for the quick fix 👍  :3!
